# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1cac65ab94fa57b6c28ffdbbb7a1ddc4dfc71d5d1d43b15b865cf4c783733c77c60b8216f2a674cdd323c4b3429d498c5f0e539e91028ee257b272bd16a60c4

test:
  secret_key_base: f188f6ee7f579e6e908a7b40311b720b97365343d965eb18f3e93c32d1600e8676f6830acb7fcab1ae0245be8419906662a87c3b48a9a5d262cc66ebf4dee6ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
